Repository castlehyeon/Team4_kosa_final, pull requests merged in 2023-10, with the labels that each got.

#96 Refactor#93 seonghyeon
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/DwaggerService.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/models/CacheDwaggerModels.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/META-INF/maven/com.douzone.comet.service.hr.dwagger/douzone-comet-service-hr-dwagger/pom.properties
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/DwaggerService.class
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/models/CacheDwaggerModels.class
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/dao/Essodm01400_x10005Dao.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/ChartData.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/ChartDataByWeek.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/OffApply.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/resources/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/META-INF/maven/com.douzone.comet.service.hr.essodm/douzone-comet-service-hr-essodm/pom.properties
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/dao/Essodm01400_x10005Dao.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/front/Dwagger_SearchService.html
  castlehyeon/front/ESSODM01400_X10005_Modal.html
  castlehyeon/front/ESSODM01400_X10005_Sub.html
  castlehyeon/front/ESSODM01400_x10005.html
Labels: 🪲BugFix, ✨Feature, 🔧Refactor

#98 Feat#87 mina
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/HRPamprg00100_X10005Service.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/HRPamprg00100_X10005_BulkUploadService.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/dao/Pamprg00100_X10005Dao.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/models/Pamprg00100_X10005Model.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/utills/CommonUtil.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/resources/mybatis/com/Pamprg00100_X10005Dao.xml
  minaci1/back/douzone-comet-service-hr-pamprg/target/classes/META-INF/maven/com.douzone.comet.service/douzone-comet-service-hr-pamprg/pom.properties
  minaci1/front/PAMPRG00100_COPY.html
  minaci1/front/PAMPRG00100_EXCEL_POP.html
  minaci1/front/PAMPRG00100_X10005.html
  minaci1/front/PAMPRG00100_YM.html
Labels: 🪲BugFix

#100 Refactor#97 seonghyeon
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/models/CacheDwaggerModels.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/META-INF/maven/com.douzone.comet.service.hr.dwagger/douzone-comet-service-hr-dwagger/pom.properties
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/models/CacheDwaggerModels.class
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/dao/Essodm01400_x10005Dao.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/ResponseHashMap.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/utils/GenerateREQ_NO.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/resources/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/META-INF/maven/com.douzone.comet.service.hr.essodm/douzone-comet-service-hr-essodm/pom.properties
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/dao/Essodm01400_x10005Dao.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/models/ResponseHashMap.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/utils/GenerateREQ_NO.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/front/ESSODM01400_X10005_Modal.html
  castlehyeon/front/ESSODM01400_X10005_Sub.html
  castlehyeon/front/ESSODM01400_x10005.html
Labels: 🪲BugFix, 🔧Refactor

#105 Refactor#78 devjangdae
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/src/main/java/com/douzone/comet/service/hr/pamodm/HRPamodm01800_X10005Service.java
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/src/main/resources/mybatis/com/Pamodm01800_X10005Dao.xml
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/target/classes/.gitignore
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/target/classes/META-INF/maven/com.douzone.comet.service/douzone-comet-service-hr-pamodm-x10005/pom.properties
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/target/classes/com/douzone/comet/service/hr/pamodm/HRPamodm01800_X10005Service.class
  devjangdae/back/douzone-comet-service-hr-pamodm-x10005/target/classes/mybatis/com/Pamodm01800_X10005Dao.xml
  devjangdae/front/PAMODM01800_X10005.html
  devjangdae/front/PAMODM01800_X10005_EMP_POP.html
  devjangdae/front/PAMODM01800_empCode_X10005.html
Labels: 🔧Refactor

#113 Refactor#101 seonghyeon
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/DwaggerService.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/utils/APIDataCall.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/.gitignore
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/META-INF/MANIFEST.MF
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/META-INF/maven/com.douzone.comet.service.hr.dwagger/douzone-comet-service-hr-dwagger/pom.properties
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/DwaggerService.class
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/utils/APIDataCall.class
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/test-classes/.gitignore
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/.gitignore
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/META-INF/MANIFEST.MF
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/META-INF/maven/com.douzone.comet.service.hr.essodm/douzone-comet-service-hr-essodm/pom.properties
  castlehyeon/front/Dwagger_SearchService.html
Labels: 🪲BugFix

#116 #112 mina
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/HRPamprg00100_X10005Service.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/dao/Pamprg00100_X10005Dao.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/java/com/douzone/comet/service/hr/pamprg/models/Pamprg00100_X10005Model.java
  minaci1/back/douzone-comet-service-hr-pamprg/src/main/resources/mybatis/com/Pamprg00100_X10005Dao.xml
  minaci1/back/douzone-comet-service-hr-pamprg/target/classes/META-INF/maven/com.douzone.comet.service/douzone-comet-service-hr-pamprg/pom.properties
  minaci1/front/PAMPRG00100_X10005.html
Labels: ✨Feature

#120 Bug fix#114 seonghyeon
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/ChartDataByWeek.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/models/OffApply.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/resources/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/front/ESSODM01400_x10005.html
Labels: 🪲BugFix

#122 bugfix: 카드리스트 검색 시 대소문자 구별없이 검색가능하도록 구현
  castlehyeon/front/Dwagger_SearchService.html
  castlehyeon/front/card_Modify_full.html
Labels: 🪲BugFix

#127 Bug fix#126 seonghyeon
  castlehyeon/back/douzone-comet-service-hr-dwagger/src/main/java/com/douzone/comet/service/hr/dwagger/DwaggerService.java
  castlehyeon/back/douzone-comet-service-hr-dwagger/target/classes/com/douzone/comet/service/hr/dwagger/DwaggerService.class
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/java/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.java
  castlehyeon/back/douzone-comet-service-hr-essodm/src/main/resources/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/com/douzone/comet/service/hr/essodm/HREssodm01400_X10005Service.class
  castlehyeon/back/douzone-comet-service-hr-essodm/target/classes/mybatis/com/Essodm01400_x10005Dao.xml
  castlehyeon/front/Dwagger_SearchService.html
  castlehyeon/front/ESSODM01400_X10005_Modal.html
  castlehyeon/front/ESSODM01400_X10005_Sub.html
  castlehyeon/front/ESSODM01400_x10005.html
  castlehyeon/front/card_Modify_full.html
Labels: 🪲BugFix
